### ISSUE TITLE
MS OneDrive broken.

### ISSUE THREAD

**Issue by chezzer64** [Deyda/NeverRed#80]
Looks like Evergreen v2405.943 introduced a change where Architecture "AMD64" is now returned as "x64", this has broken the MS OneDrive Download. May also impact any other NeverRed Apps where it looks for Architecture -eq "AMD64". 

![image](https://github.com/Deyda/NeverRed/assets/30706006/cb66a361-d3f5-4d6b-b641-b0edca9d41d4)

**Comment by chezzer64** [comment]
Had a quick look through the NeverRed ps1 script and don't see any other references to AMD64, so think this only impacts MS OneDrive.

**Comment by Deyda** [comment]
I'm on Version 2405.959 of the Evergreen Powershell Module and dont see any x64 Architecture entries....only AMD64

**Comment by Deyda** [comment]
![image](https://github.com/Deyda/NeverRed/assets/59874195/d3774d9b-c47b-49f3-8562-a59636705283)

**Comment by chezzer64** [comment]
Hmm Interesting, I'm using Enterprise Ring for OneDrive and it returns x64 instead of AMD64:

```
Get-InstalledModule -Name Evergreen

Version    Name                                Repository           Description
-------    ----                                ----------           -----------
2405.959   Evergreen                           PSGallery            Create evergreen Windows image builds with the l...
```

```
Get-EvergreenApp -Name MicrosoftOneDrive -ErrorAction SilentlyContinue | Where-Object { $_.Ring -eq "Enterprise" -and $_.Type -eq "Exe"}


Version      : 24.010.0114.0003
Throttle     : 100
Architecture : x86
Ring         : Enterprise
Sha256       : GMY/sY6tFPc9aQVnx4VDdSFM+eNPrnIfeP5PyG9k1M8=
Type         : exe
URI          : https://oneclient.sfx.ms/Win/Installers/24.010.0114.0003/OneDriveSetup.exe

Version      : 24.010.0114.0003
Throttle     : 100
Architecture : ARM64
Ring         : Enterprise
Type         : exe
Sha256       : SVlAS1Y6mBO9Lm7jYarSZhNRZWdgA9t23Bc2cfEsw5A=
URI          : https://oneclient.sfx.ms/Win/Installers/24.010.0114.0003/arm64/OneDriveSetup.exe

Version      : 24.010.0114.0003
Throttle     : 100
Architecture : x64
Ring         : Enterprise
Type         : exe
Sha256       : bQKiXhD0QZduhW2WcsF0pcLj+ZZuyik08vcBwA0r+/Y=
URI          : https://oneclient.sfx.ms/Win/Installers/24.010.0114.0003/amd64/OneDriveSetup.exe


```

**Comment by chezzer64** [comment]
If I do run the same query as you (for Production Ring), I see x64 returned, not AMD64:

```
Get-EvergreenApp -Name MicrosoftOneDrive -ErrorAction SilentlyContinue | Where-Object { $_.Ring -eq "Production" -and $_.Type -eq "Exe"}


Version      : 24.078.0416.0003
Throttle     : 1
Architecture : x86
Ring         : Production
Sha256       : cj7zD1wlHcB/PVnG7IFD4Jt5ElSZmOEjXHjadRMtul0=
Type         : exe
URI          : https://oneclient.sfx.ms/Win/Installers/24.078.0416.0003/OneDriveSetup.exe

Version      : 24.078.0416.0003
Throttle     : 1
Architecture : x64
Ring         : Production
Type         : exe
Sha256       : McMdl2DNb0ub/tqB8W9eR/IKzUTNj27hDDq6MngvG/I=
URI          : https://oneclient.sfx.ms/Win/Installers/24.078.0416.0003/amd64/OneDriveSetup.exe

Version      : 24.078.0416.0003
Throttle     : 1
Architecture : ARM64
Ring         : Production
Type         : exe
Sha256       : PSIwThnrgnt9e6KVa6di4YdBwe/nA19yqfjehP0Ev38=
URI          : https://oneclient.sfx.ms/Win/Installers/24.078.0416.0003/arm64/OneDriveSetup.exe

Version      : 24.076.0414.0005
Throttle     : 100
Architecture : x86
Ring         : Production
Sha256       : 4lkW4ZE8lv8PuD9w9KCgst8FWP0+y+Z1kf3Qt4tbYoE=
Type         : exe
URI          : https://oneclient.sfx.ms/Win/Installers/24.076.0414.0005/OneDriveSetup.exe

Version      : 24.076.0414.0005
Throttle     : 100
Architecture : ARM64
Ring         : Production
Type         : exe
Sha256       : ea1BrbQohvHyjBH4t7g0gKjT3Ro7JiPoOeOzU2lhxrU=
URI          : https://oneclient.sfx.ms/Win/Installers/24.076.0414.0005/arm64/OneDriveSetup.exe

Version      : 24.076.0414.0005
Throttle     : 100
Architecture : x64
Ring         : Production
Type         : exe
Sha256       : UBhGPQ9EVi5XepKnZ/6AQ40wrti7h2hqefx/t8AT5l8=
URI          : https://oneclient.sfx.ms/Win/Installers/24.076.0414.0005/amd64/OneDriveSetup.exe
```

**Comment by Deyda** [comment]
result with ps5

![image](https://github.com/Deyda/NeverRed/assets/59874195/704a9c19-fb49-408f-a3de-f2720c75b11a)

**Comment by chezzer64** [comment]
Mine is a fresh build with Evergreen module newly installed - is your machine using an older (cached) version of Evergreen perhaps?

**Comment by chezzer64** [comment]
Perhaps NeverRed is not updating correctly to a new version of the Evergreen PS Module when it detects and installs a new version of the module??

**Comment by chezzer64** [comment]
If you run Get-EvergreenApp with -verbose option, is it showing that modules from the 2405.959 folder are being used?

```
Get-EvergreenApp -Name MicrosoftOneDrive -ErrorAction SilentlyContinue -verbose | Where-Object { $_.Ring -eq "Enterprise" -and $_.Type -eq "Exe"}
VERBOSE: Function path: C:\Program Files\WindowsPowerShell\Modules\Evergreen\2405.959\Apps\Get-MicrosoftOneDrive.ps1
VERBOSE: Function exists: C:\Program Files\WindowsPowerShell\Modules\Evergreen\2405.959\Apps\Get-MicrosoftOneDrive.ps1.
VERBOSE: Dot sourcing: C:\Program Files\WindowsPowerShell\Modules\Evergreen\2405.959\Apps\Get-MicrosoftOneDrive.ps1.
VERBOSE: Get-FunctionResource: read application resource strings from [C:\Program Files\WindowsPowerShell\Modules\Evergreen\2405.959\Manifests\MicrosoftOneDrive.json]
........

```

**Comment by chezzer64** [comment]
So I just ran a test on a machine that had an older release of Evergreen PS Module installed. I then ran NeverRed and allowed it to update to latest version of Evergreen module, which it appeared to do successfully:

```
Get-InstalledModule -Name Evergreen

Version              Name                                Repository           Description
-------              ----                                ----------           -----------
2405.959             Evergreen                           PSGallery            Create evergreen Windows image builds with the latest versions of applications. Evergreen is a simple PowerShell module that retrieves the latest vers...
```

....but if I then run a Get-EvergreenApp with -verbose, I see it is still referencing the old version of the Evergreen module:

```
Get-EvergreenApp -Name MicrosoftOneDrive -ErrorAction SilentlyContinue -verbose | Where-Object { $_.Ring -eq "Enterprise" -and $_.Type -eq "Exe"}
VERBOSE: Function path: C:\Program Files\WindowsPowerShell\Modules\Evergreen\2404.928\Apps\Get-MicrosoftOneDrive.ps1
VERBOSE: Function exists: C:\Program Files\WindowsPowerShell\Modules\Evergreen\2404.928\Apps\Get-MicrosoftOneDrive.ps1.
VERBOSE: Dot sourcing: C:\Program Files\WindowsPowerShell\Modules\Evergreen\2404.928\Apps\Get-MicrosoftOneDrive.ps1.
VERBOSE: Get-FunctionResource: read application resource strings from [C:\Program Files\WindowsPowerShell\Modules\Evergreen\2404.928\Manifests\MicrosoftOneDrive.json]
VERBOSE: Calling: Get-MicrosoftOneDrive.
VERBOSE: Invoke-EvergreenWebRequest: Adding ContentType.
VERBOSE: Invoke-EvergreenWebRequest: Using temp file C:\Users\AzureAdmin\AppData\Local\Temp\tmp67E0.tmp.
VERBOSE: Invoke-EvergreenWebRequest: Invoke-WebRequest parameter: UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0..
VERBOSE: Invoke-EvergreenWebRequest: Invoke-WebRequest parameter: ContentType: application/xml; charset=utf-8.
VERBOSE: Invoke-EvergreenWebRequest: Invoke-WebRequest parameter: UseBasicParsing: True.
VERBOSE: Invoke-EvergreenWebRequest: Invoke-WebRequest parameter: Method: Default.
VERBOSE: Invoke-EvergreenWebRequest: Invoke-WebRequest parameter: Uri: https://g.live.com/1rewlive5skydrive/OneDriveEnterpriseV2.
VERBOSE: Invoke-EvergreenWebRequest: Invoke-WebRequest parameter: PassThru: True.
VERBOSE: Invoke-EvergreenWebRequest: Invoke-WebRequest parameter: OutFile: C:\Users\AzureAdmin\AppData\Local\Temp\tmp67E0.tmp.
VERBOSE: GET https://g.live.com/1rewlive5skydrive/OneDriveEnterpriseV2 with 0-byte payload
VERBOSE: received 899-byte response of content type application/xml
VERBOSE: Invoke-EvergreenWebRequest: Response: 200.
VERBOSE: Invoke-EvergreenWebRequest: Content type: application/xml.
VERBOSE: Invoke-EvergreenWebRequest: Returning content of length: 8.
VERBOSE: Get-FileType: found extension: [exe]
VERBOSE: Get-Architecture: Architecture not found in https://oneclient.sfx.ms/Win/Installers/24.010.0114.0003/OneDriveSetup.exe, defaulting to x86.
VERBOSE: Get-FileType: found extension: [exe]
VERBOSE: Invoke-EvergreenWebRequest: Adding ContentType.
VERBOSE: Invoke-EvergreenWebRequest: Using temp file C:\Users\AzureAdmin\AppData\Local\Temp\tmp681F.tmp.
VERBOSE: Invoke-EvergreenWebRequest: Invoke-WebRequest parameter: UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0..
VERBOSE: Invoke-EvergreenWebRequest: Invoke-WebRequest parameter: ContentType: application/xml; charset=utf-8.
VERBOSE: Invoke-EvergreenWebRequest: Invoke-WebRequest parameter: UseBasicParsing: True.
VERBOSE: Invoke-EvergreenWebRequest: Invoke-WebRequest parameter: Method: Default.
VERBOSE: Invoke-EvergreenWebRequest: Invoke-WebRequest parameter: Uri: https://g.live.com/1rewlive5skydrive/MsitFastV2.
VERBOSE: Invoke-EvergreenWebRequest: Invoke-WebRequest parameter: PassThru: True.
VERBOSE: Invoke-EvergreenWebRequest: Invoke-WebRequest parameter: OutFile: C:\Users\AzureAdmin\AppData\Local\Temp\tmp681F.tmp.
VERBOSE: GET https://g.live.com/1rewlive5skydrive/MsitFastV2 with 0-byte payload
VERBOSE: received 896-byte response of content type application/xml
VERBOSE: Invoke-EvergreenWebRequest: Response: 200.
VERBOSE: Invoke-EvergreenWebRequest: Content type: application/xml.
VERBOSE: Invoke-EvergreenWebRequest: Returning content of length: 8.
VERBOSE: Get-FileType: found extension: [exe]
VERBOSE: Get-Architecture: Architecture not found in https://oneclient.sfx.ms/Win/Installers/24.087.0429.0001/OneDriveSetup.exe, defaulting to x86.
VERBOSE: Get-FileType: found extension: [exe]
VERBOSE: Invoke-EvergreenWebRequest: Adding ContentType.
VERBOSE: Invoke-EvergreenWebRequest: Using temp file C:\Users\AzureAdmin\AppData\Local\Temp\tmp684F.tmp.
VERBOSE: Invoke-EvergreenWebRequest: Invoke-WebRequest parameter: UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0..
VERBOSE: Invoke-EvergreenWebRequest: Invoke-WebRequest parameter: ContentType: application/xml; charset=utf-8.
VERBOSE: Invoke-EvergreenWebRequest: Invoke-WebRequest parameter: UseBasicParsing: True.
VERBOSE: Invoke-EvergreenWebRequest: Invoke-WebRequest parameter: Method: Default.
VERBOSE: Invoke-EvergreenWebRequest: Invoke-WebRequest parameter: Uri: https://g.live.com/1rewlive5skydrive/OneDriveProductionV2.
VERBOSE: Invoke-EvergreenWebRequest: Invoke-WebRequest parameter: PassThru: True.
VERBOSE: Invoke-EvergreenWebRequest: Invoke-WebRequest parameter: OutFile: C:\Users\AzureAdmin\AppData\Local\Temp\tmp684F.tmp.
VERBOSE: GET https://g.live.com/1rewlive5skydrive/OneDriveProductionV2 with 0-byte payload
VERBOSE: received 1779-byte response of content type application/xml
VERBOSE: Invoke-EvergreenWebRequest: Response: 200.
VERBOSE: Invoke-EvergreenWebRequest: Content type: application/xml.
VERBOSE: Invoke-EvergreenWebRequest: Returning content of length: 13.
VERBOSE: Get-FileType: found extension: [exe]
VERBOSE: Get-Architecture: Architecture not found in https://oneclient.sfx.ms/Win/Installers/24.076.0414.0005/OneDriveSetup.exe, defaulting to x86.
VERBOSE: Get-FileType: found extension: [exe]
VERBOSE: Get-FileType: found extension: [exe]
VERBOSE: Get-Architecture: Architecture not found in https://oneclient.sfx.ms/Win/Installers/24.078.0416.0003/OneDriveSetup.exe, defaulting to x86.
VERBOSE: Get-FileType: found extension: [exe]
VERBOSE: Invoke-EvergreenWebRequest: Adding ContentType.
VERBOSE: Invoke-EvergreenWebRequest: Using temp file C:\Users\AzureAdmin\AppData\Local\Temp\tmp687F.tmp.
VERBOSE: Invoke-EvergreenWebRequest: Invoke-WebRequest parameter: UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0..
VERBOSE: Invoke-EvergreenWebRequest: Invoke-WebRequest parameter: ContentType: application/xml; charset=utf-8.
VERBOSE: Invoke-EvergreenWebRequest: Invoke-WebRequest parameter: UseBasicParsing: True.
VERBOSE: Invoke-EvergreenWebRequest: Invoke-WebRequest parameter: Method: Default.
VERBOSE: Invoke-EvergreenWebRequest: Invoke-WebRequest parameter: Uri: https://g.live.com/1rewlive5skydrive/MsitSlowV2.
VERBOSE: Invoke-EvergreenWebRequest: Invoke-WebRequest parameter: PassThru: True.
VERBOSE: Invoke-EvergreenWebRequest: Invoke-WebRequest parameter: OutFile: C:\Users\AzureAdmin\AppData\Local\Temp\tmp687F.tmp.
VERBOSE: GET https://g.live.com/1rewlive5skydrive/MsitSlowV2 with 0-byte payload
VERBOSE: received 896-byte response of content type application/xml
VERBOSE: Invoke-EvergreenWebRequest: Response: 200.
VERBOSE: Invoke-EvergreenWebRequest: Content type: application/xml.
VERBOSE: Invoke-EvergreenWebRequest: Returning content of length: 8.
VERBOSE: Get-FileType: found extension: [exe]
VERBOSE: Get-Architecture: Architecture not found in https://oneclient.sfx.ms/Win/Installers/24.086.0428.0001/OneDriveSetup.exe, defaulting to x86.
VERBOSE: Get-FileType: found extension: [exe]
VERBOSE: Invoke-EvergreenWebRequest: Adding ContentType.
VERBOSE: Invoke-EvergreenWebRequest: Using temp file C:\Users\AzureAdmin\AppData\Local\Temp\tmp68CE.tmp.
VERBOSE: Invoke-EvergreenWebRequest: Invoke-WebRequest parameter: UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0..
VERBOSE: Invoke-EvergreenWebRequest: Invoke-WebRequest parameter: ContentType: application/xml; charset=utf-8.
VERBOSE: Invoke-EvergreenWebRequest: Invoke-WebRequest parameter: UseBasicParsing: True.
VERBOSE: Invoke-EvergreenWebRequest: Invoke-WebRequest parameter: Method: Default.
VERBOSE: Invoke-EvergreenWebRequest: Invoke-WebRequest parameter: Uri: https://g.live.com/1rewlive5skydrive/OneDriveInsiderV2.
VERBOSE: Invoke-EvergreenWebRequest: Invoke-WebRequest parameter: PassThru: True.
VERBOSE: Invoke-EvergreenWebRequest: Invoke-WebRequest parameter: OutFile: C:\Users\AzureAdmin\AppData\Local\Temp\tmp68CE.tmp.
VERBOSE: GET https://g.live.com/1rewlive5skydrive/OneDriveInsiderV2 with 0-byte payload
VERBOSE: received 899-byte response of content type application/xml
VERBOSE: Invoke-EvergreenWebRequest: Response: 200.
VERBOSE: Invoke-EvergreenWebRequest: Content type: application/xml.
VERBOSE: Invoke-EvergreenWebRequest: Returning content of length: 8.
VERBOSE: Get-FileType: found extension: [exe]
VERBOSE: Get-Architecture: Architecture not found in https://oneclient.sfx.ms/Win/Installers/24.083.0423.0001/OneDriveSetup.exe, defaulting to x86.
VERBOSE: Get-FileType: found extension: [exe]


Version      : 24.010.0114.0003
Throttle     : 100
Architecture : x86
Ring         : Enterprise
Sha256       : GMY/sY6tFPc9aQVnx4VDdSFM+eNPrnIfeP5PyG9k1M8=
Type         : exe
URI          : https://oneclient.sfx.ms/Win/Installers/24.010.0114.0003/OneDriveSetup.exe

Version      : 24.010.0114.0003
Throttle     : 100
Architecture : ARM64
Ring         : Enterprise
Type         : exe
Sha256       : SVlAS1Y6mBO9Lm7jYarSZhNRZWdgA9t23Bc2cfEsw5A=
URI          : https://oneclient.sfx.ms/Win/Installers/24.010.0114.0003/arm64/OneDriveSetup.exe

Version      : 24.010.0114.0003
Throttle     : 100
Architecture : AMD64
Ring         : Enterprise
Type         : exe
Sha256       : bQKiXhD0QZduhW2WcsF0pcLj+ZZuyik08vcBwA0r+/Y=
URI          : https://oneclient.sfx.ms/Win/Installers/24.010.0114.0003/amd64/OneDriveSetup.exe

```

**Comment by chezzer64** [comment]
Suggested fix. After running `Update-Module Evergreen -Force` , run `Import-Module Evergreen -Force` to ensure the latest version is loaded into the session.

e.g.:

```
Write-Host "Update Evergreen module."
Update-Module Evergreen -force
Import-Module Evergreen -force
Write-Host -ForegroundColor Green "Update Evergreen module done."
```

Likewise for the other PS Modules that NeverRed leverages (e.g. Nevergreen, etc).

**Comment by Deyda** [comment]
Solved in Version 2.10.32 thx

**Comment by sjeanjean** [comment]
The version 2.10.33 reversed the correction from the version 2.10.32

The download of MicrosoftOneDrive doesn't work.

**Comment by sjeanjean** [comment]
You forgot to bump the version. The script loop on the auto-update.
Line 4157 : $eVersion = "2.10.33"

**Comment by Deyda** [comment]
done thx
