### ISSUE TITLE
Mozilla Firefox 404

### ISSUE THREAD

**Issue by Janstie** [Deyda/NeverRed#87]
Error msg in download logs look like this:

_PS>TerminatingError(Invoke-WebRequest): "404 page not found
"
PS>TerminatingError(Invoke-WebRequest): "404 page not found
"
PS>TerminatingError(Invoke-WebRequest): "404 page not found
"
PS>TerminatingError(Invoke-WebRequest): "404 page not found
"
PS>TerminatingError(Invoke-WebRequest): "404 page not found
"
PS>TerminatingError(Invoke-WebRequest): "404 page not found
"
PS>TerminatingError(Invoke-WebRequest): "404 page not found
"
PS>TerminatingError(Invoke-WebRequest): "404 page not found
"
PS>TerminatingError(Invoke-WebRequest): "404 page not found
"
PS>TerminatingError(Invoke-WebRequest): "404 page not found
"
PS>TerminatingError(Invoke-WebRequest): "404 page not found
"
PS>TerminatingError(Invoke-WebRequest): "404 page not found
"
PS>TerminatingError(Invoke-WebRequest): "404 page not found
"
PS>TerminatingError(Invoke-WebRequest): "404 page not found
"
Download Mozilla Firefox ESR English x64
Download Version:
Current Version:
No new version available_

Get-EvergreenApp -Name "MozillaFirefox" looks fine:

_Version      : 115.11.0
Architecture : x86
Channel      : Extended Support
Language     : en-US
Type         : msix
Filename     : Firefox Setup 115.11.0esr.msix
URI          : https://download-installer.cdn.mozilla.net/pub/firefox/releases/115.11.0esr/win32/multi/Firefox%20Setup%
               20115.11.0esr.msix

Version      : 115.11.0
Architecture : x64
Channel      : Extended Support
Language     : en-US
Type         : msi
Filename     : Firefox Setup 115.11.0esr.msi
URI          : https://download-installer.cdn.mozilla.net/pub/firefox/releases/115.11.0esr/win64/en-US/Firefox%20Setup%
               20115.11.0esr.msi

Version      : 115.11.0
Architecture : x64
Channel      : Extended Support
Language     : en-US
Type         : msix
Filename     : Firefox Setup 115.11.0esr.msix
URI          : https://download-installer.cdn.mozilla.net/pub/firefox/releases/115.11.0esr/win64/multi/Firefox%20Setup%
               20115.11.0esr.msix_

If you need additonal information, please let me know

**Comment by Deyda** [comment]
Solved in Version 2.10.37

**Comment by Janstie** [comment]
Good Morning and thanks for the fast response!

But still the same problem, website is reachable with the source.

(https://download-installer.cdn.mozilla.net/pub/firefox/releases/115.11.0esr/win64/en-US/Firefox%20Setup%
20115.11.0esr.msi)

PS>TerminatingError(Invoke-WebRequest): "404 page not found
"
PS>TerminatingError(Invoke-WebRequest): "404 page not found
"
PS>TerminatingError(Invoke-WebRequest): "404 page not found
"
PS>TerminatingError(Invoke-WebRequest): "404 page not found
"
PS>TerminatingError(Invoke-WebRequest): "404 page not found
"
PS>TerminatingError(Invoke-WebRequest): "404 page not found
"
PS>TerminatingError(Invoke-WebRequest): "404 page not found
"
PS>TerminatingError(Invoke-WebRequest): "404 page not found
"
PS>TerminatingError(Invoke-WebRequest): "404 page not found
"
PS>TerminatingError(Invoke-WebRequest): "404 page not found
"
PS>TerminatingError(Invoke-WebRequest): "404 page not found
"
PS>TerminatingError(Invoke-WebRequest): "404 page not found
"
PS>TerminatingError(Invoke-WebRequest): "404 page not found
"
PS>TerminatingError(Invoke-WebRequest): "404 page not found
"
Download Mozilla Firefox FIREFOX_ESR English x64
Download Version:
Current Version:
No new version available

**Comment by Deyda** [comment]
Solved with the newest version
